### ISSUE TITLE
ERR_MODULE_NOT_FOUND 

### ISSUE THREAD

**Issue by timahey** [mayudev/revcord#12]
Hello, when using the npm start command, an error ERR_MODULE_NOT_FOUND occurs.

![image](https://github.com/mayudev/revcord/assets/69219228/1cd67b5a-45da-401c-8ab0-1a9ece156816)

Any ideas how to fix it?

**Comment by mayudev** [comment]
did you run `npm install` and `npm run build`?

**Comment by timahey** [comment]
Yes

**Comment by mayudev** [comment]
I am not sure what its caused by then, maybe try cloning the repo again and doing everything from the beginning

**Comment by timahey** [comment]
Just did it all over again. But again the same error. I also noticed that when `npm install` warning `npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs` is displayed, maybe an error occurs because of it?
![image](https://github.com/mayudev/revcord/assets/69219228/6c8a57d6-1d44-4bab-917f-bb5c59556336)

**Comment by mayudev** [comment]
no, it is very unlikely to be caused by that since it is only a warning
This might be a Windows-specific issue since I cannot reproduce it on Linux, I will try it tomorrow on a virtual machine

**Comment by mayudev** [comment]
Okay, I was actually able to accidentally reproduce this issue. It seems I'm getting an identical output while omitting the `--experimental-specifier-resolution=node` part, but I'm using an older version of node. I believe this parameter was removed in node v20, which causes the issue

**Comment by timahey** [comment]
Okay, thanks for the answer

**Comment by mayudev** [comment]
It turns out the fix was pretty easy, I just had to configure tsc to emit commonjs modules, and so it works without any experimental loader. I probably thought that method was outdated, but since the nodejs ecosystem is a mess it is still the only way to have things working on most versions.
I briefly tested it in node 16, 18 and 20 and everything seems to be working properly now.
