### ISSUE TITLE
Embed error !

### ISSUE THREAD

**Issue by raymand211092** [mayudev/revcord#13]
WARN Discord Failed to translate embed.
WARN Discord TypeError: Cannot read properties of undefined (reading 'toRevolt')
WARN Discord     at file:///root/revcord/build/app/discord.js:200:88
WARN Discord     at Generator.next (<anonymous>)
WARN Discord     at file:///root/revcord/build/app/discord.js:7:71
WARN Discord     at new Promise (<anonymous>)
WARN Discord     at __awaiter (file:///root/revcord/build/app/discord.js:3:12)
WARN Discord     at handleDiscordMessage (file:///root/revcord/build/app/discord.js:100:12)
WARN Discord     at Client.<anonymous> (file:///root/revcord/build/app/Bot.js:98:13)
WARN Discord     at Client.emit (node:events:513:28)
WARN Discord     at MessageCreateAction.handle (/root/revcord/node_modules/discord.js/src/client/actions/MessageCreate.js:28:14)
WARN Discord     at Object.module.exports [as MESSAGE_CREATE] (/root/revcord/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)

**Comment by mayudev** [comment]
It seems there was a bug that caused Discord embeds without a title field to not be returned. Fixed in 107f1f26105886344157849343b7688c3d397134
