### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by windowz414** [mayudev/revcord#2]
Hello, I wanted to use this for bridging my Discord server and WIP Revolt server, but I got this error when I tried doing `npm start`.

Full trace can be found here: https://hastebin.com/xemuhokabo

Would be really glad if you could help!

**Comment by mayudev** [comment]
It tells you to install `sqlite3` manually, which most likely means something went wrong when you were doing `npm install`.

sqlite3 requires some native modules to be compiled, so you need to have `g++` and `make` (and possibly python) in your system. If you don't, install them and then do `npm install sqlite3`.

If it doesn't work, delete `node_modules` and do `npm install` again. I think this should help.

**Comment by windowz414** [comment]
> It tells you to install `sqlite3` manually, which most likely means something went wrong when you were doing `npm install`.
> 
> sqlite3 requires some native modules to be compiled, so you need to have `g++` and `make` (and possibly python) in your system. If you don't, install them and then do `npm install sqlite3`.
> 
> If it doesn't work, delete `node_modules` and do `npm install` again. I think this should help.

Well, I'm mainly using the machine I tried this on to build Android, so `g++` and `make` are present.

I tried manually installing `sqlite3` through `npm install sqlite3`, it was the same.

I'm now giving deletion of `node_modules` a shot, and returns me some missing modules, like `dotenv`, which I'm handling manually right now. Thanks for the help!

**Comment by windowz414** [comment]
Quick update: Issue has been resolved!

For future viewers, if you're getting some output like I do on the first post, do these after attempting to do `npm start` or `nodemon` or whatever you use as start;
```bash
# Install sqlite3 and dotenv as user
npm install sqlite3 dotenv

# Remove node_modules present in repository
rm -rf node_modules

# Now start
npm start
```

Thank you @mayudev for mentioning removal of `node_modules` and so getting this resolved! I'll be adding up some troubleshooting things as PR towards README so whoever visiting this project can see what to do on such issue. :)
