### ISSUE TITLE
Placing

### ISSUE THREAD

**Issue by PossibleSnow** [mayudev/revcord#20]
Where do i place the .env file? like the directory?

**Comment by PossibleSnow** [comment]
`C:\Users\knigh>git clone https://github.com/mayudev/revcord
Cloning into 'revcord'...
remote: Enumerating objects: 668, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (89/89), done.
Receiving objects: 100% (668/668), 587.85 KiB | 4.45 MiB/s, done. 495

Resolving deltas: 100% (427/427), done.

C:\Users\knigh>cd revcord

C:\Users\knigh\revcord>npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

added 210 packages, and audited 211 packages in 21s

19 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

C:\Users\knigh\revcord>npm run build

> revcord@1.1.1 build
> tsc


C:\Users\knigh\revcord>npm start

> revcord@1.1.1 start
> node build/index.js


C:\Users\knigh\revcord\build\app\Main.js:28
            throw "At least one token was not provided";
            ^
At least one token was not provided
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.16.1

C:\Users\knigh\revcord>npm start

> revcord@1.1.1 start
> node build/index.js


C:\Users\knigh\revcord\build\app\Main.js:28
            throw "At least one token was not provided";
            ^
At least one token was not provided
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.16.1

C:\Users\knigh\revcord>node --trace-uncaught ...
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'C:\Users\knigh\revcord\...'
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:922:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:23:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
Thrown at:
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at executeUserEntryPoint (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47


Node.js v18.16.1
`

**Comment by PossibleSnow** [comment]
i placed the .env under app directory.

**Comment by mayudev** [comment]
The .env file should be placed in the root directory of the app, so `revcord` directory.
