### ISSUE TITLE
use message.reply insted of a embed

### ISSUE THREAD

**Issue by Aldair69** [mayudev/revcord#36]
yeah, nothing else to say

**Comment by darkfessing** [comment]
Is this project still alive? Coul`d be very usefull, while supported.

**Comment by Aldair502-fuck** [comment]
> s this project still alive? Coul`d be very usefull, while supported.

nope, use the spearated bridge of automod.

**Comment by darkfessing** [comment]
> spearated bridge of automod

Whats that? Can you share a link?

**Comment by darkfessing** [comment]
Everything works men. Checked. Duno what are you talking here about..

**Comment by Aldair69** [comment]
> Everything works men. Checked. Duno what are you talking here about..
>> Whats that? Can you share a link?
Automod removed bridge function, if u are searching a updated bridge bot use automod from that repo
