### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by rain23764** [mayudev/revcord#8]
hi i just installed Node.js v18.15.0, later i open and try to paste on it it shows

Welcome to Node.js v18.15.0.
Type ".help" for more information.
> git clone https://github.com/mayudev/revcord
git clone https://github.com/mayudev/revcord
    ^^^^^

Uncaught SyntaxError: Unexpected identifier

something is wrong?
![node_rRe2oE5Ucv](https://user-images.githubusercontent.com/127510235/224330821-578aaa46-e973-43c3-bc1a-e84f7c0200a2.png)

**Comment by rain23764** [comment]
https://git-scm.com/
is this git for windows?

**Comment by mayudev** [comment]
yes

**Comment by rain23764** [comment]
Place the relevant tokens in environment variables. The easiest way is to create a .env file (yes, a file called .env):
now i can i make .env file?

**Comment by raluvy95** [comment]
You can create new file in the folder you cloned called ".env" and then open it with Notepad (right click on newly created file) and then append the following code:
```sh
REVOLT_TOKEN="..."
DISCORD_TOKEN="..."
```
Replace the dots with your revolt bot token as well as your discord bot token.

After that, open new command prompt, then go to the folder you cloned (usually called "revcord") and type `npm i`, then `npm run start`

Sorry for late reply, but I just saw your issue.
